# .yml takes priority over .properties
spring:

app:
  datasources:
    postgres:
      required: true
      jdbc-url: jdbc:postgresql://host.docker.internal:5432/frosthand_postgres_db
      username: frosthand_postgres_username
      password: frosthand_postgres_password
      driver-class-name: org.postgresql.Driver

    oracle:
      jdbc-url: jdbc:oracle:thin:@host.docker.internal:1521:XEPDB1
      username: system
      password: frosthand_oracle_password
      driver-class-name: oracle.jdbc.OracleDriver

    mssql:
      jdbc-url: jdbc:sqlserver://host.docker.internal:1433;databaseName=db
      username: sa
      password: frosthand_mssql_password123*!
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

#    h2:
#      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true